spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      #ddl-auto: none / create-drop / create / update / validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:h2:~/test; #메모리
#    url: jdbc:h2:file:E:/_개인 개발 공부/신규 문제은행/DB/H2/bank
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  key: 12345678901234567890123456789012

server:
  servlet:
    encoding:
      force-response: true

logging:
  level:
    root: info
    org.springframework.web.cline: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
  file:
    path: /logs